### ISSUE TITLE
TypeError: No matching definition for argument type(s) array(uint8, 3d, C), array(uint8, 2d, C)

### ISSUE THREAD

**Issue by Ha-coding-user** [zhangzw12319/lcps#10]
Hello, While running the code with nuScenes v1.0-mini data, the following error occurred.
All of Error message in here.

 File "C:\Users\MLCF\Desktop\하준우\논문\Autonomous-Vehicle\3D semantic segmentation\LiDAR_Panoptic_segmentation\lidar-panoptic\LCPS1\lcps\train.py", line 518, in <module>
    main()
  File "C:\Users\MLCF\Desktop\하준우\논문\Autonomous-Vehicle\3D semantic segmentation\LiDAR_Panoptic_segmentation\lidar-panoptic\LCPS1\lcps\train.py", line 440, in main
    for i_iter, train_dict in enumerate(train_dataset_loader):
  File "C:\Users\MLCF\anaconda3\envs\LCPS1\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "C:\Users\MLCF\anaconda3\envs\LCPS1\lib\site-packages\torch\utils\data\dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "C:\Users\MLCF\anaconda3\envs\LCPS1\lib\site-packages\torch\utils\data\dataloader.py", line 1359, in _process_data
    data.reraise()
  File "C:\Users\MLCF\anaconda3\envs\LCPS1\lib\site-packages\torch\_utils.py", line 543, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\MLCF\anaconda3\envs\LCPS1\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\MLCF\anaconda3\envs\LCPS1\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\MLCF\anaconda3\envs\LCPS1\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\MLCF\Desktop\하준우\논문\Autonomous-Vehicle\3D semantic segmentation\LiDAR_Panoptic_segmentation\lidar-panoptic\LCPS1\lcps\dataloader\dataset.py", line 565, in __getitem__
    voxel_label = nb_process_label(np.copy(voxel_label), label_voxel_pair.astype(np.uint8))
  File "C:\Users\MLCF\anaconda3\envs\LCPS1\lib\site-packages\numba\core\dispatcher.py", line 703, in _explain_matching_error
    raise TypeError(msg)
TypeError: No matching definition for argument type(s) array(uint8, 3d, C), array(uint8, 2d, C)

How to solve this Error... Please comment me

**Comment by Ha-coding-user** [comment]
Okay. I solved this Error

If, someone meet above error, you can solve like this way.

In file lcps/dataloader/dataset.py line 581,
change code 
processed_inst = nb_process_inst(np.copy(processed_inst), inst_voxel_pair.astype)
to
processed_inst = nb_process_inst(np.copy(processed_inst), inst_voxel_pair.astype(np.int64))

**Comment by zhangzw12319** [comment]
Yes, you're correct. `i8` means `int64` in the numba [doc](https://numba.readthedocs.io/en/stable/reference/types.html). Thanks for your kind info here.
